### ISSUE TITLE
Why in the forward function of FP16 module the output is converted back to FP32?  I get out of memory error on this multiple times.

### ISSUE THREAD

**Issue by willanxywc** [jojotenya/LAMOL#2]
```
class FP16_Module(nn.Module): 
     def init(self, module): 
           super(FP16_Module, self).init() 
           self.add_module('module', module.half())
    def forward(self, inputs, **kwargs): 
           return fp16_to_fp32(self.module((fp32_to_fp16(inputs)), **kwargs))  
```
Worth noting that I get CUDA out of memory error for many times on the above piece of code, fp16_to_fp32(self.module(*(fp32_to_fp16(inputs)), **kwargs)). I have to reduce the memory size and train batchsize to avoid that error. Data parallel doesn't seem to help. I run the code on 4 GeForce 2080 cards and the out of memory error throws out as usual.

**Comment by luotuoqingshan** [comment]
Same here, how do you solve that?

**Comment by Daikon-Sun** [comment]
I am not 100% sure, but I think it is because the calculation of loss function is unstable if FP16 is used, so we have to cast it back into FP32.
But this is the old way of doing mixed precision training.
You should use the new Apex or the mixed precision training built into pytorch.
