### ISSUE TITLE
Scores

### ISSUE THREAD

**Issue by KonceptBlast** [jojotenya/LAMOL#4]
Congratulations on your great work!
I have a problem with reproducing some of your scores from the paper.
I assume all the scores reported by you in the paper (not only in Table 2) have been obtained with GPT-2.

|             | SQuAD | WikiSQL | SST  | SRL  | WOZ  | AGNews | Amazon | DBPedia |
|-------------|-------|---------|------|------|------|--------|--------|---------|
| GPT-2 score | 72.3  |   70.7  | 90.9 | 70.4 | 84.9 |  94.6  |  62.3  |   99.1  |
| My scores   | 72.7  |   **65.0**  | 91.8 | **64.5** | **64.3** |  93.2  |  **54.7**  |   99.1  |

Above are your scores from the Table 2 (in your paper) and my scores when I've tried to replicate them. I marked with bold results that differ quite a bit. I'm not sure, maybe I've run the code in a wrong way, so please take a look at the command I've executed:
`./train.sh --seq_train_type lll --tasks amazon --model_name gpt2` 
where I've only replaced `amazon` with other tasks like `wikisql`, `srl`, `woz.en` etc.

**Comment by chho33** [comment]
Hi KonceptBlast,
Thank you for your question.
Our default setting of epoch number in our code is 3. However, in our paper, we use 9 as our epoch number. Please add --n_train_epochs 9 after ./train.sh to reproduce our result.

**Comment by KonceptBlast** [comment]
@jojotenya thanks a lot! Now I'm getting results much closer to yours:
WikiSQL - 70.1
SRL - 70.3
WOZ - 85.8
Amazon - 58.2 (slightly off, perhaps I should do several runs and take the average score)

I have one more question - what commands I should execute to get the results from Table 3, for:

1. ![image](https://user-images.githubusercontent.com/6275422/83958142-9cdfc100-a86e-11ea-8603-0be2fc98c4ec.png)
2. ![image](https://user-images.githubusercontent.com/6275422/83958155-c3056100-a86e-11ea-81ff-f2da27719df1.png)
3. ![image](https://user-images.githubusercontent.com/6275422/83958162-d0bae680-a86e-11ea-9452-50743097f967.png)

**Comment by KonceptBlast** [comment]
@jojotenya or @Daikon-Sun could you confirm if the following commands are correct to get results from Table 3? 

**1.** `./train.sh --seq_train_type lll --tasks sst srl woz.en --model_name gpt2 --n_train_epochs 9 --gen_lm_sample_percentage 0.2` 
and 
`./test.sh --seq_train_type lll --tasks sst srl woz.en --model_name gpt2 --n_train_epochs 9 --gen_lm_sample_percentage 0.2`

**2.** `./train.sh --seq_train_type lll --tasks sst srl woz.en --model_name gpt2 --n_train_epochs 9 --gen_lm_sample_percentage 0.2 --add_task_tokens` 
and 
`./test.sh --seq_train_type lll --tasks sst srl woz.en --model_name gpt2 --n_train_epochs 9 --gen_lm_sample_percentage 0.2 --add_task_tokens`

**3.** `./train.sh --seq_train_type lll --tasks sst srl woz.en --model_name gpt2 --n_train_epochs 9 --gen_lm_sample_percentage 0.2 --real_sample` 
and 
`./test.sh --seq_train_type lll --tasks sst srl woz.en --model_name gpt2 --n_train_epochs 9 --gen_lm_sample_percentage 0.2 --real_sample`

Thanks in advance

**Comment by chho33** [comment]
@KonceptBlast 
Yes, it corrects. Sorry being late.
